Transform: AWS::Serverless-2016-10-31

Resources:
  findJobsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: findJobs/
      Handler: app.findJobsHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 2048
      Layers:
        - !Ref upworkApplyBotLayer
      # Events:
      #   1minute:
      #     Type: Schedule
      #     Properties:
      #       Schedule: rate(1 hour)
      #       Description: run job collecting every 1 hour
      #       Enabled: true
  # -------------------------------
  submitProposalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: submitProposal/
      Handler: app.submitProposalHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 2048
      Layers:
        - !Ref upworkApplyBotLayer
  # -------------------------------
  triggerLambasForAccountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: triggerLambasForAccounts/
      Handler: app.triggerLambasForAccountsHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 1024
      Layers:
        - !Ref upworkApplyBotLayer
  # -------------------------------
  upworkApplyBotLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: upworkApplyBotDependencies/
      LayerName: twitterOutreacherLayer
      Description: layer for upworkApplyBot project
      CompatibleRuntimes:
        - nodejs20.x
        - nodejs18.x
        - nodejs16.x
